# Generated by Django 2.2.5 on 2020-11-27 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201127_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.date(2020, 11, 27)),
            preserve_default=False,
        ),
    ]
